"""create core tables

Revision ID: da10e22fa9ea
Revises:
Create Date: 2026-07-04 17:52:41.937745

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "da10e22fa9ea"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_outbox",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("topic", sa.String(length=128), nullable=False),
        sa.Column("aggregate_type", sa.String(length=64), nullable=False),
        sa.Column("aggregate_id", sa.BigInteger(), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "published", "failed", name="outbox_status"),
            nullable=False,
        ),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_event_outbox_status", "event_outbox", ["status"], unique=False)
    op.create_index("idx_event_outbox_topic", "event_outbox", ["topic"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=128), nullable=True),
        sa.Column("role", sa.Enum("admin", "member", name="user_role"), nullable=False),
        sa.Column(
            "status", sa.Enum("active", "disabled", name="user_status"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username", name="uk_users_username"),
    )
    op.create_index("idx_users_role", "users", ["role"], unique=False)
    op.create_table(
        "meetings",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("meeting_time", sa.DateTime(), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum("audio", "manual_text", name="meeting_source_type"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("draft", "processing", "ready", "failed", name="meeting_status"),
            nullable=False,
        ),
        sa.Column("created_by", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_meetings_created_by", "meetings", ["created_by"], unique=False)
    op.create_index(
        "idx_meetings_meeting_time", "meetings", ["meeting_time"], unique=False
    )
    op.create_index("idx_meetings_status", "meetings", ["status"], unique=False)
    op.create_table(
        "audio_files",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("meeting_id", sa.BigInteger(), nullable=False),
        sa.Column("original_name", sa.String(length=255), nullable=False),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("uploaded_by", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meetings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_audio_files_meeting_id", "audio_files", ["meeting_id"], unique=False
    )
    op.create_table(
        "meeting_participants",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("meeting_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("participant_name", sa.String(length=64), nullable=False),
        sa.Column("is_ai_detected", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meetings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_participants_meeting_id",
        "meeting_participants",
        ["meeting_id"],
        unique=False,
    )
    op.create_index(
        "idx_participants_user_id", "meeting_participants", ["user_id"], unique=False
    )
    op.create_table(
        "asr_jobs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("meeting_id", sa.BigInteger(), nullable=False),
        sa.Column("audio_file_id", sa.BigInteger(), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "processing", "succeeded", "failed", name="asr_job_status"
            ),
            nullable=False,
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["audio_file_id"],
            ["audio_files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meetings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_asr_jobs_meeting_id", "asr_jobs", ["meeting_id"], unique=False)
    op.create_index("idx_asr_jobs_status", "asr_jobs", ["status"], unique=False)
    op.create_table(
        "meeting_transcripts",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("meeting_id", sa.BigInteger(), nullable=False),
        sa.Column("asr_job_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "source_type",
            sa.Enum("audio_asr", "manual_text", name="transcript_source_type"),
            nullable=False,
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("language", sa.String(length=32), nullable=True),
        sa.Column("created_by", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asr_job_id"],
            ["asr_jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meetings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_transcripts_meeting_id",
        "meeting_transcripts",
        ["meeting_id"],
        unique=False,
    )
    op.create_index(
        "idx_transcripts_source_type",
        "meeting_transcripts",
        ["source_type"],
        unique=False,
    )
    op.create_table(
        "ai_jobs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("meeting_id", sa.BigInteger(), nullable=False),
        sa.Column("transcript_id", sa.BigInteger(), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "processing", "succeeded", "failed", name="ai_job_status"
            ),
            nullable=False,
        ),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meetings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["transcript_id"],
            ["meeting_transcripts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_ai_jobs_meeting_id", "ai_jobs", ["meeting_id"], unique=False)
    op.create_index("idx_ai_jobs_status", "ai_jobs", ["status"], unique=False)
    op.create_table(
        "meeting_summaries",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("meeting_id", sa.BigInteger(), nullable=False),
        sa.Column("ai_job_id", sa.BigInteger(), nullable=False),
        sa.Column("topic", sa.String(length=200), nullable=False),
        sa.Column("participants_json", sa.JSON(), nullable=False),
        sa.Column("key_points_json", sa.JSON(), nullable=False),
        sa.Column("decisions_json", sa.JSON(), nullable=False),
        sa.Column("raw_model_output", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ai_job_id"],
            ["ai_jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meetings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_summaries_meeting_id", "meeting_summaries", ["meeting_id"], unique=False
    )
    op.create_index(
        "uk_summary_ai_job_id", "meeting_summaries", ["ai_job_id"], unique=True
    )
    op.create_table(
        "todo_drafts",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("meeting_id", sa.BigInteger(), nullable=False),
        sa.Column("ai_job_id", sa.BigInteger(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("assignee_name", sa.String(length=64), nullable=True),
        sa.Column("assignee_id", sa.BigInteger(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("source_sentence", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column(
            "status",
            sa.Enum("draft", "confirmed", "discarded", name="draft_status"),
            nullable=False,
        ),
        sa.Column("confirmed_task_id", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ai_job_id"],
            ["ai_jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["assignee_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meetings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_todo_drafts_meeting_id", "todo_drafts", ["meeting_id"], unique=False
    )
    op.create_index("idx_todo_drafts_status", "todo_drafts", ["status"], unique=False)
    op.create_table(
        "tasks",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("meeting_id", sa.BigInteger(), nullable=False),
        sa.Column("draft_id", sa.BigInteger(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("assignee_id", sa.BigInteger(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("todo", "doing", "done", name="task_status"),
            nullable=False,
        ),
        sa.Column("confirmed_by", sa.BigInteger(), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assignee_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["confirmed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["draft_id"],
            ["todo_drafts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["meeting_id"],
            ["meetings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_tasks_assignee_status", "tasks", ["assignee_id", "status"], unique=False
    )
    op.create_index("idx_tasks_due_date", "tasks", ["due_date"], unique=False)
    op.create_index("idx_tasks_meeting_id", "tasks", ["meeting_id"], unique=False)
    op.create_foreign_key(
        "fk_todo_drafts_confirmed_task_id",
        "todo_drafts",
        "tasks",
        ["confirmed_task_id"],
        ["id"],
    )
    op.create_table(
        "task_status_logs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("task_id", sa.BigInteger(), nullable=False),
        sa.Column("from_status", sa.String(length=32), nullable=True),
        sa.Column("to_status", sa.String(length=32), nullable=False),
        sa.Column("changed_by", sa.BigInteger(), nullable=False),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.Column("changed_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["changed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_task_logs_task_id", "task_status_logs", ["task_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_todo_drafts_confirmed_task_id", "todo_drafts", type_="foreignkey"
    )
    op.drop_index("idx_task_logs_task_id", table_name="task_status_logs")
    op.drop_table("task_status_logs")
    op.drop_index("idx_tasks_meeting_id", table_name="tasks")
    op.drop_index("idx_tasks_due_date", table_name="tasks")
    op.drop_index("idx_tasks_assignee_status", table_name="tasks")
    op.drop_table("tasks")
    op.drop_index("idx_todo_drafts_status", table_name="todo_drafts")
    op.drop_index("idx_todo_drafts_meeting_id", table_name="todo_drafts")
    op.drop_table("todo_drafts")
    op.drop_index("uk_summary_ai_job_id", table_name="meeting_summaries")
    op.drop_index("idx_summaries_meeting_id", table_name="meeting_summaries")
    op.drop_table("meeting_summaries")
    op.drop_index("idx_ai_jobs_status", table_name="ai_jobs")
    op.drop_index("idx_ai_jobs_meeting_id", table_name="ai_jobs")
    op.drop_table("ai_jobs")
    op.drop_index("idx_transcripts_source_type", table_name="meeting_transcripts")
    op.drop_index("idx_transcripts_meeting_id", table_name="meeting_transcripts")
    op.drop_table("meeting_transcripts")
    op.drop_index("idx_asr_jobs_status", table_name="asr_jobs")
    op.drop_index("idx_asr_jobs_meeting_id", table_name="asr_jobs")
    op.drop_table("asr_jobs")
    op.drop_index("idx_participants_user_id", table_name="meeting_participants")
    op.drop_index("idx_participants_meeting_id", table_name="meeting_participants")
    op.drop_table("meeting_participants")
    op.drop_index("idx_audio_files_meeting_id", table_name="audio_files")
    op.drop_table("audio_files")
    op.drop_index("idx_meetings_status", table_name="meetings")
    op.drop_index("idx_meetings_meeting_time", table_name="meetings")
    op.drop_index("idx_meetings_created_by", table_name="meetings")
    op.drop_table("meetings")
    op.drop_index("idx_users_role", table_name="users")
    op.drop_table("users")
    op.drop_index("idx_event_outbox_topic", table_name="event_outbox")
    op.drop_index("idx_event_outbox_status", table_name="event_outbox")
    op.drop_table("event_outbox")
    # ### end Alembic commands ###
